# Generated by Django 3.2.7 on 2021-10-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_lists', '0003_auto_20211002_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='password',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='done',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='todo',
            name='details',
            field=models.TextField(),
        ),
    ]
