# Generated by Django 3.2.7 on 2021-10-02 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_lists', '0005_alter_todo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
