# Generated by Django 3.2.7 on 2021-10-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_lists', '0008_auto_20211003_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='text',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
