# Generated by Django 3.2.7 on 2021-10-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_lists', '0009_project_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='done',
            name='text',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='text',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='text',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
