# Generated by Django 3.2.7 on 2021-10-05 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_lists', '0011_todo_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='resources',
        ),
    ]
