# Generated by Django 3.2.7 on 2021-10-05 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_lists', '0012_remove_todo_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='text',
        ),
    ]
