# Generated by Django 3.2.7 on 2021-10-13 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_lists', '0013_remove_project_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.FileField(upload_to='resources')),
            ],
        ),
        migrations.CreateModel(
            name='wiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='wikis')),
            ],
        ),
        migrations.AlterField(
            model_name='done',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_lists.todo'),
        ),
    ]
